### ISSUE TITLE
Can't complete the authentication process

### ISSUE THREAD

**Issue by TheDudeV2** [AzureAD/azure-activedirectory-library-for-objc#349]
Hello,
We are trying to authenticate an Azure Mobile Services iOS Application with an ADFS 3.0 system and are running into troubles.

First, we had an issue when attempting to login.  After the user entered her username@domain, the 'redirecting' animation would continue forever.  We have solved this issue by using the following method:

authContext acquireTokenWithResource:resourceURI clientId:clientID redirectUri:redirectURI userId:NULL extraQueryParameters:@"domain_hint=***********************.com" completionBlock:^(ADAuthenticationResult *result) {

This allows us to bypass the realm discovery process and be presented with the login form straight away.

However, upon submission of this form, we get the following error returned from the server:
2015-07-02 10:46:01.527 ********************[27028:2619515] done logging in. Errors: Error Domain=com.Microsoft.WindowsAzureMobileServices.ErrorDomain Code=-1301 "The server returned an error." UserInfo=0x7fa532c73870 {NSLocalizedDescription=The server returned an error.}

From the Azure Mobile Services Logs:
Log entry details
ERROR
Message='Authentication failed', Exception=System.IdentityModel.Tokens.AudienceUriValidationFailedException: Jwt10303: Audience validation failed. jwt.Audience: 'https://graph.windows.net'. Could not match:  validationParameters.AllowedAudience: 'null' and validationParameters.AllowedAudiences: 'https://************************.azure-mobile.net/login/aad'
   at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateAudience(JwtSecurityToken jwt, TokenValidationParameters validationParameters)
   at System.IdentityModel.Tokens.JwtSecurityTokenHandler.ValidateToken(String jwtEncodedString, TokenValidationParameters validationParameters)
   at Microsoft.Owin.Security.Jwt.JwtFormat.Unprotect(String protectedText)
   at Microsoft.Owin.Security.OAuth.OAuthBearerAuthenticationHandler.<AuthenticateCoreAsync>d__0.MoveNext(), Id=00000000-0000-0000-0000-000000000000, Category='Microsoft.Owin.Security.OAuth.OAuthBearerAuthenticationMiddleware'

Any ideas?

**Comment by RPangrle** [comment]
Do you have any logs you can share?

ADAL relies on logging quite a bit: https://github.com/AzureAD/azure-activedirectory-library-for-objc#logs
